name: Release Firmware

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to create release

    defaults:
      run:
        working-directory: ./firmware

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "14.2.Rel1"

      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Build Firmware
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/gcc-arm-none-eabi.cmake
          cmake --build build

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: firmware/build/firmware.bin # Root path needed
