name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./firmware

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build-essential # Contains gcc and standard C libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run Unity tests
        run: |
          chmod u+x tests/unit/run_tests.sh
          ./tests/unit/run_tests.sh

  renode-tests:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./firmware

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "14.2.Rel1"

      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Build Firmware
        run: |
          cmake -B build_simulation -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/gcc-arm-none-eabi.cmake -DSIMULATION=ON
          cmake --build build_simulation

      - name: Run Renode tests
        uses: antmicro/renode-test-action@v5
        with:
          tests-to-run: firmware/tests/renode/src/*.robot
